config/routes.rb
Rails.application.routes.draw do
  resources :attachments

  resources :announcements

  resources :homepages

  resources :support_messages
  get '/help', to: 'support_messages#new', as: :help
  get '/updates', to: 'static_pages#updates', as: :updates

  devise_for :users, :controllers => { :invitations => 'users/invitations' }

  mount RailsAdmin::Engine => '/superadmin', :as => 'rails_admin'

  resources :alerts do
    resources :comments
    resources :collaborations
    post '/remove_tag', to: 'alerts#remove_tag', as: :remove_tag
    post '/archive',    to: 'alerts#archive',     as: :archive
    collection do
      patch '/archive', to: 'alerts#archive_all', as: :archive_all
    end
  end


  resources :events do
    resources :comments
  end

  resources :posts do
    resources :comments
  end

  resources :billing, only: [:new]

  resources :hoas, except: [:show] do
    collection do
      get 'check_subdomain_name'
    end
  end

  get '/organisation',          to: 'hoas#show',       as: :organisation
  get '/organisation/members',  to: 'hoas#members',    as: :members
  get '/organisation/settings', to: 'hoas#edit',   as: :settings

  get '/organisation/billing',         to: 'billing#index',    as: :billing
  get '/organisation/billing/renew',   to: 'billing#renew_subscription',    as: :renew
  get '/organisation/billing/confirm', to: 'billing#confirm_payment', as: :confirm_payment

  resources :participations
  resources :users, only: [:show, :edit, :update]
  post '/users/:id/remove', to: 'users#remove_from_hoa', as: :remove_from_hoa
  post '/users/:id/change_role', to: 'users#change_role', as: :change_role

  get '/welcome', to: 'hoas#new', as: :welcome

  get   '/profile',         to: 'profile#index',  as: :profile
  get   '/profile/edit',    to: 'profile#edit',   as: :edit_profile
  patch '/profile/update',  to: 'profile#update', as: :update_profile

  get '/export', to: 'hoas#export', as: :export

  constraints(Subdomain) do
    get '/' => 'homepages#show', as: :public_homepage
  end

  root to: 'hoas#show'

  post '/ufgjdiie/:id', to: 'admin#change_hoa', as: :change_hoa

  require 'sidekiq/web'
  authenticate :user, lambda { |u| true } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/hoa.rb
# == Schema Information
#
# Table name: hoas
#
#  id                :integer          not null, primary key
#  name              :string(255)
#  created_at        :datetime
#  updated_at        :datetime
#  subdomain_name    :string(255)
#  subscription_type :string(255)      default("basic")
#  subscribed_until  :datetime
#  address           :string(255)
#  city              :string(255)
#  postal_code       :string(255)
#  kvk               :string(255)
#  account_nr        :string(255)
#  account_owner     :string(255)
#  allow_posts       :boolean          default(TRUE)
#

class Hoa < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper

  validates :name, :subdomain_name, presence: true
  validates :subdomain_name, uniqueness: true

  resourcify

  has_many :posts
  has_many :alerts
  has_many :users
  has_many :events
  has_many :announcements
  has_many :payments
  has_many :attachments
  has_one :homepage

  def subscription
    subscription_type == 'standard' ? 'Standaard' : 'Basis'
  end

  def subscribed?
    subscribed_until &&
    subscribed_until > DateTime.now &&
    subscription_type == 'standard'
  end

  def storage_used
    number_to_human_size(attachments.sum(:file_size))
  end
end

app/controllers/hoas_controller.rb
class HoasController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_hoa, only: [:billing, :members, :edit, :update, :destroy, :export]
  after_action :verify_authorized, :except => [:show, :index, :create, :check_subdomain_name, :export]

  # GET /hoas
  def index
    @hoas = Hoa.all
    authorize @hoas
  end

  # GET /hoas/1
  def show
    redirect_to welcome_path unless current_user.hoa
    current_user.hoa ? set_activities : @activities = []
    @post = Post.new user: current_user

    @unread_alerts = current_user.hoa.alerts.unread_by(current_user)
  end

  # GET /hoas/new
  def new
    @hoa = Hoa.new
    authorize @hoa
  end

  # GET /hoas/1/edit
  def edit
    authorize @hoa
  end

  # POST /hoas
  def create
    @hoa = Hoa.new(hoa_params)

    if @hoa.save
      @hoa.users << current_user
      current_user.add_role :moderator, @hoa
      redirect_to organisation_url(subdomain: current_user.hoa.subdomain_name), notice: 'Jouw vereniging is aangemaakt, gefeliciteerd!'
    else
      render 'new'
    end
  end

  # PATCH/PUT /hoas/1
  def update
    authorize @hoa
    if @hoa.update(hoa_params)
      redirect_to organisation_path, notice: 'Vereniging aangepast.'
    else
      render 'edit'
    end
  end

  # DELETE /hoas/1
  def destroy
    authorize @hoa
    @hoa.destroy
    redirect_to hoas_url, notice: 'Hoa was successfully destroyed.'
  end

  def members
    authorize @hoa
    @moderators        = @hoa.users.with_role(:moderator, current_user.hoa)
    @maintenance_staff = @hoa.users.with_role(:maintenance, current_user.hoa)
    @owners            = @hoa.users - @moderators - @maintenance_staff
  end

  def billing
    authorize @hoa
  end

  def check_subdomain_name
    if valid_subdomain_name?(params[:name])
      render nothing: true, status: 200
    else
      render nothing: true, status: 409
    end
  end

  def export
    render text: @hoa.alerts.to_csv
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hoa
      @hoa = current_user.hoa
    end

    # Only allow a trusted parameter "white list" through.
    def hoa_params
      params.require(:hoa).permit(:name, :subdomain_name, :address, :postal_code, :city, :allow_posts)
    end

    def set_activities
      @activities = PublicActivity::Activity
        .where(hoa_id: current_user.hoa.id)
        .includes(:owner, trackable: [:hoa])
        .order('created_at desc')
        .limit(20)
    end

    def valid_subdomain_name?(name)
      Hoa.where(subdomain_name: name).count == 0 &&
      name.length < 21
    end
end

app/views/hoas/_form.html.haml
= form_for(@hoa) do |f|
  - if @hoa.errors.any?
    #error_explanation
      %h2
        = pluralize(@hoa.errors.count, "error")
        prohibited this hoa from being saved:
      %ul
        - @hoa.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .actions
    = f.submit

app/views/hoas/_member_list.html.haml
.ui.celled.small.selection.list
  - members.each do |member|
    .item.hover-show
      %img.ui.avatar.image{ src: gravatar_url(member) }
      = link_to user_path(member), class: 'content' do
        .header= member.full_name
        .description= member.email

      - if current_user.has_role?(:moderator, current_user.hoa) && member != current_user
        .ui.small.basic.buttons.right.floated
          = link_to 'Aanpassen', edit_user_path(member), class: 'ui button', id: "edit-user-#{member.id}"
          .ui.tiny.blue.floating.dropdown.icon.button
            %i.dropdown.icon
            .menu

              - unless member.has_role? :moderator, member.hoa
                .item
                  = link_to change_role_path(member, user: {role: 'moderator'}), method: :post, id: "change-to-moderator-#{member.id}" do
                    Maak bestuurder

              - unless member.has_role? :maintenance, member.hoa
                .item
                  = link_to change_role_path(member, user: {role: 'maintenance'}), method: :post, id: "change-to-maintenance-#{member.id}" do
                    Maak huismeester

              - if member.has_role?(:moderator, member.hoa) or member.has_role?(:maintenance, member.hoa)
                .item
                  = link_to change_role_path(member, user: {role: ''}), method: :post, id: "change-to-owner-#{member.id}" do
                    Maak eigenaar


              .item
                = link_to remove_from_hoa_path(member), method: :post, id: "remove-#{member.id}" do
                  Verwijder uit vereniging

      - if current_user == member
        = link_to 'Pas mijn profiel aan', edit_profile_path, class: 'ui small basic button right floated'

app/views/hoas/billing.html.haml
- @active_tab     = 'home'
- @active_button  = 'billing'

.row
  = render 'dashboard/sidebuttons'

  .small-10.column
    .ui.segment

      %h1.header
        Facturatie

      .ui.green.message
        Voorlopig is Domici.ly nog onbetaald. Bij verandering brengen we je op de hoogte.

      .ui.large.relaxed.list
        .item
          = link_to new_billing_path, class: 'right floated ui button' do
            Verleng abonnement
          .content
            .header Looptijd
            Je abonnement loopt nog tot xx

    %table.ui.table.segment
      %h2 Betalingen
      %thead
        %th Bedrag
        %th Kenmerk
        %th Datum

      %tbody
        %tr
          %td 100
          %td basis abonnement 1 juni - 1 september
          %td 1 juni

app/views/hoas/edit.html.haml
- @active_tab     = 'home'
- @active_button  = 'settings'

.row
  .small-9.small-centered.column
    .ui.segment

      = form_for @hoa do |f|
        .ui.form
          .field
            %label Naam vereniging
            = f.text_field :name

          .field
            %label Adres van vereniging
            = f.text_field :address

          .field
            %label Postcode
            = f.text_field :postal_code

          .field
            %label Plaats
            = f.text_field :city

          .inline.field
            .ui.toggle.checkbox
              = f.check_box :allow_posts
              %label Sta het toe dat iedereen berichten op de updates pagina kan plaatsen.

        .ui.submit
          = f.submit 'Sla aanpassingen op', class: 'ui blue button'

app/views/hoas/index.html.haml
%h1 Listing hoas
%table
  %thead
    %tr
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @hoas.each do |hoa|
      %tr
        %td= hoa.name
        %td= link_to 'Show', hoa
        %td= link_to 'Edit', edit_hoa_path(hoa)
        %td= link_to 'Destroy', hoa, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Hoa', new_hoa_path

app/views/hoas/members.html.haml
- @active_button  = 'members'

.row
  .small-12.column
    - if current_user.has_role?(:moderator, current_user.hoa) or current_user.admin
      = link_to new_user_invitation_path, id: 'new-member' do
        .ui.blue.domicily-blue.labeled.icon.button
          %i.add.icon
          Nieuwe Leden

      .float-right
        = link_to settings_path, id: 'settings' do
          .ui.labeled.icon.button
            %i.settings.icon
            Domici.ly Opties

        = link_to billing_path, id: 'billing' do
          .ui.labeled.icon.button
            %i.payment.icon
            Betalingen

    .ui.raised.segment
      - if ! @moderators.empty?
        .ui.green.ribbon.label
          Bestuurders
        = render 'member_list', members: @moderators

      - if ! @maintenance_staff.empty?
        %br
        .ui.blue.ribbon.label
          Huismeesters
        = render 'member_list', members: @maintenance_staff

      - if ! @owners.empty?
        %br
        .ui.teal.ribbon.label
          Eigenaars
        = render 'member_list', members: @owners

app/views/hoas/new.html.haml
- @active_tab = 'welcome'
- @flat = true
.row
  .medium-6.small-12.medium-centered.column
    .sign-in

      %h1.ui.header
        Stap 2/2
        .sub.header
          Maak je vereniging aan

      = form_for @hoa do |f|

        %label Naam vereniging
        = f.text_field :name

        .flat-field
          %label Kies een domein
          = f.text_field :subdomain_name, "data-validate" => "/hoas/check_subdomain_name", "data-err" => "Domeinnaam is niet beschikbaar. Kies iets anders!", autocomplete: "off"

        .ui.small.message
          .header#subdomain_full
            naam.domici.ly
          .content
            Dit is waar je straks jouw vereniging kan vinden.

        %label Adres van vereniging
        = f.text_field :address

        %label Postcode
        = f.text_field :postal_code

        %label Plaats
        = f.text_field :city


        .ui.submit
          = f.submit 'Maak mijn vereniging aan', class: 'flat-button'

app/views/hoas/show.html.haml
- @active_tab     = 'home'
- @quick_add_bar = true

.row
  .small-9.column
    = render 'dashboard/top_form'
    - @activities.each do |activity|
      = render_activity activity
    
  .small-3.column
    = render 'dashboard/sidenav'  