config/routes.rb
Rails.application.routes.draw do
  resources :attachments

  resources :announcements

  resources :homepages

  resources :support_messages
  get '/help', to: 'support_messages#new', as: :help
  get '/updates', to: 'static_pages#updates', as: :updates

  devise_for :users, :controllers => { :invitations => 'users/invitations' }

  mount RailsAdmin::Engine => '/superadmin', :as => 'rails_admin'

  resources :alerts do
    resources :comments
    resources :collaborations
    post '/remove_tag', to: 'alerts#remove_tag', as: :remove_tag
    post '/archive',    to: 'alerts#archive',     as: :archive
    collection do
      patch '/archive', to: 'alerts#archive_all', as: :archive_all
    end
  end


  resources :events do
    resources :comments
  end

  resources :posts do
    resources :comments
  end

  resources :billing, only: [:new]

  resources :hoas, except: [:show] do
    collection do
      get 'check_subdomain_name'
    end
  end

  get '/organisation',          to: 'hoas#show',       as: :organisation
  get '/organisation/members',  to: 'hoas#members',    as: :members
  get '/organisation/settings', to: 'hoas#edit',   as: :settings

  get '/organisation/billing',         to: 'billing#index',    as: :billing
  get '/organisation/billing/renew',   to: 'billing#renew_subscription',    as: :renew
  get '/organisation/billing/confirm', to: 'billing#confirm_payment', as: :confirm_payment

  resources :participations
  resources :users, only: [:show, :edit, :update]
  post '/users/:id/remove', to: 'users#remove_from_hoa', as: :remove_from_hoa
  post '/users/:id/change_role', to: 'users#change_role', as: :change_role

  get '/welcome', to: 'hoas#new', as: :welcome

  get   '/profile',         to: 'profile#index',  as: :profile
  get   '/profile/edit',    to: 'profile#edit',   as: :edit_profile
  patch '/profile/update',  to: 'profile#update', as: :update_profile

  get '/export', to: 'hoas#export', as: :export

  constraints(Subdomain) do
    get '/' => 'homepages#show', as: :public_homepage
  end

  root to: 'hoas#show'

  post '/ufgjdiie/:id', to: 'admin#change_hoa', as: :change_hoa

  require 'sidekiq/web'
  authenticate :user, lambda { |u| true } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/homepage.rb
# == Schema Information
#
# Table name: homepages
#
#  id             :integer          not null, primary key
#  created_at     :datetime
#  updated_at     :datetime
#  subdomain_name :string(255)
#  hoa_id         :integer
#

class Homepage < ActiveRecord::Base
  belongs_to :hoa
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  before_action :set_homepage, only: [:destroy]
  before_action :set_homepage_by_subdomain, only: [:show, :edit, :update]
  before_filter :authenticate_user!, except: [:show]

  # GET /homepages
  def index
    @homepages = Homepage.all
  end

  # GET /homepages/1
  def show
    # TODO Replace by call to @homepage.title
    # @title = @homepage.hoa.name
    # @hoa = find_hoa_by_subdomain
    redirect_to new_user_session_path
  end

  # GET /homepages/new
  def new
    @homepage = Homepage.new
  end

  # GET /homepages/1/edit
  def edit
  end

  # POST /homepages
  def create
    @homepage = Homepage.new(homepage_params)

    if @homepage.save
      redirect_to @homepage, notice: 'Homepage was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /homepages/1
  def update
    if @homepage.update(homepage_params)
      redirect_to @homepage, notice: 'Homepage was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /homepages/1
  def destroy
    @homepage.destroy
    redirect_to homepages_url, notice: 'Homepage was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homepage
      @homepage = Homepage.find(params[:id])
    end

    def set_homepage_by_subdomain
      @homepage = Homepage.find_by(subdomain_name:request.subdomain)
    end

    def find_hoa_by_subdomain
      Hoa.find_by(subdomain_name: request.subdomain)
    end

    # Only allow a trusted parameter "white list" through.
    def homepage_params
      params[:homepage]
    end
end

app/views/homepages/_form.html.haml
= form_for @homepage do |f|
  - if @homepage.errors.any?
    #error_explanation
      %h2= "#{pluralize(@homepage.errors.count, "error")} prohibited this homepage from being saved:"
      %ul
        - @homepage.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/homepages/edit.html.haml
%h1 Editing homepage

= render 'form'

= link_to 'Show', @homepage
\|
= link_to 'Back', homepages_path

app/views/homepages/index.html.haml
%h1 Listing homepages

%table
  %tr
    %th
    %th
    %th

  - @homepages.each do |homepage|
    %tr
      %td= link_to 'Show', homepage
      %td= link_to 'Edit', edit_homepage_path(homepage)
      %td= link_to 'Destroy', homepage, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Homepage', new_homepage_path

app/views/homepages/new.html.haml
%h1 New homepage

= render 'form'

= link_to 'Back', homepages_path

app/views/homepages/show.html.haml
- @active_tab = 'homepage'
- unless current_user
  .logo
    Domici.ly

.row
  .small-12.column

    .big-header
      -if @hoa
        %h1.title
          = @hoa.name
      -else
        %h3
          Dit subdomein is nog vrij!

      - unless current_user
        = link_to new_user_session_path, class: 'ui huge positive button' do
          Log in