config/routes.rb
Rails.application.routes.draw do
  resources :attachments

  resources :announcements

  resources :homepages

  resources :support_messages
  get '/help', to: 'support_messages#new', as: :help
  get '/updates', to: 'static_pages#updates', as: :updates

  devise_for :users, :controllers => { :invitations => 'users/invitations' }

  mount RailsAdmin::Engine => '/superadmin', :as => 'rails_admin'

  resources :alerts do
    resources :comments
    resources :collaborations
    post '/remove_tag', to: 'alerts#remove_tag', as: :remove_tag
    post '/archive',    to: 'alerts#archive',     as: :archive
    collection do
      patch '/archive', to: 'alerts#archive_all', as: :archive_all
    end
  end


  resources :events do
    resources :comments
  end

  resources :posts do
    resources :comments
  end

  resources :billing, only: [:new]

  resources :hoas, except: [:show] do
    collection do
      get 'check_subdomain_name'
    end
  end

  get '/organisation',          to: 'hoas#show',       as: :organisation
  get '/organisation/members',  to: 'hoas#members',    as: :members
  get '/organisation/settings', to: 'hoas#edit',   as: :settings

  get '/organisation/billing',         to: 'billing#index',    as: :billing
  get '/organisation/billing/renew',   to: 'billing#renew_subscription',    as: :renew
  get '/organisation/billing/confirm', to: 'billing#confirm_payment', as: :confirm_payment

  resources :participations
  resources :users, only: [:show, :edit, :update]
  post '/users/:id/remove', to: 'users#remove_from_hoa', as: :remove_from_hoa
  post '/users/:id/change_role', to: 'users#change_role', as: :change_role

  get '/welcome', to: 'hoas#new', as: :welcome

  get   '/profile',         to: 'profile#index',  as: :profile
  get   '/profile/edit',    to: 'profile#edit',   as: :edit_profile
  patch '/profile/update',  to: 'profile#update', as: :update_profile

  get '/export', to: 'hoas#export', as: :export

  constraints(Subdomain) do
    get '/' => 'homepages#show', as: :public_homepage
  end

  root to: 'hoas#show'

  post '/ufgjdiie/:id', to: 'admin#change_hoa', as: :change_hoa

  require 'sidekiq/web'
  authenticate :user, lambda { |u| true } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/attachment.rb
# == Schema Information
#
# Table name: attachments
#
#  id           :integer          not null, primary key
#  alert_id     :integer
#  attachment   :string(255)
#  created_at   :datetime
#  updated_at   :datetime
#  content_type :string(255)
#  file_size    :integer
#

class Attachment < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader
  belongs_to :alert
  belongs_to :hoa
  validates :attachment,
    presence: true,
    file_size: {
      maximum: 20.megabytes.to_i
    }

  before_save :update_attachment_attributes

  def name
    return File.basename(URI.parse(attachment.to_s).path)
  end

  private

  def update_attachment_attributes
    if attachment.present? && attachment_changed?
      self.content_type = attachment.file.content_type
      self.file_size = attachment.file.size
    end
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]

  # GET /attachments
  def index
    @attachments = Attachment.all
  end

  # GET /attachments/1
  def show
  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  # GET /attachments/1/edit
  def edit
  end

  # POST /attachments
  def create
    @attachment = Attachment.new(attachment_params)

    if @attachment.save
      redirect_to @attachment, notice: 'Attachment toegevoegd.'
    else
      render :new
    end
  end

  # PATCH/PUT /attachments/1
  def update
    if @attachment.update(attachment_params)
      redirect_to @attachment, notice: 'Attachment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /attachments/1
  def destroy
    alert = @attachment.alert
    @attachment.destroy
    redirect_to alert_path(alert), notice: 'Attachment is verwijderd.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def attachment_params
      params.require(:attachment).permit(:alert_id, :attachment)
    end
end

app/views/attachments/_form.html.haml
= form_for @attachment do |f|
  - if @attachment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@attachment.errors.count, "error")} prohibited this attachment from being saved:"
      %ul
        - @attachment.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :alert_id
    = f.number_field :alert_id
  .field
    = f.label :attachment
    = f.text_field :attachment
  .actions
    = f.submit 'Save'

app/views/attachments/edit.html.haml
%h1 Editing attachment

= render 'form'

= link_to 'Show', @attachment
\|
= link_to 'Back', attachments_path

app/views/attachments/index.html.haml
%h1 Listing attachments

%table
  %tr
    %th Alert
    %th Attachment
    %th
    %th
    %th

  - @attachments.each do |attachment|
    %tr
      %td= attachment.alert_id
      %td= attachment.attachment
      %td= link_to 'Show', attachment
      %td= link_to 'Edit', edit_attachment_path(attachment)
      %td= link_to 'Destroy', attachment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Attachment', new_attachment_path

app/views/attachments/new.html.haml
%h1 New attachment

= render 'form'

= link_to 'Back', attachments_path

app/views/attachments/show.html.haml
%p#notice= notice

%p
  %b Alert:
  = @attachment.alert_id
%p
  %b Attachment:
  = @attachment.attachment

= link_to 'Edit', edit_attachment_path(@attachment)
\|
= link_to 'Back', attachments_path