config/routes.rb
Rails.application.routes.draw do
  resources :attachments

  resources :announcements

  resources :homepages

  resources :support_messages
  get '/help', to: 'support_messages#new', as: :help
  get '/updates', to: 'static_pages#updates', as: :updates

  devise_for :users, :controllers => { :invitations => 'users/invitations' }

  mount RailsAdmin::Engine => '/superadmin', :as => 'rails_admin'

  resources :alerts do
    resources :comments
    resources :collaborations
    post '/remove_tag', to: 'alerts#remove_tag', as: :remove_tag
    post '/archive',    to: 'alerts#archive',     as: :archive
    collection do
      patch '/archive', to: 'alerts#archive_all', as: :archive_all
    end
  end


  resources :events do
    resources :comments
  end

  resources :posts do
    resources :comments
  end

  resources :billing, only: [:new]

  resources :hoas, except: [:show] do
    collection do
      get 'check_subdomain_name'
    end
  end

  get '/organisation',          to: 'hoas#show',       as: :organisation
  get '/organisation/members',  to: 'hoas#members',    as: :members
  get '/organisation/settings', to: 'hoas#edit',   as: :settings

  get '/organisation/billing',         to: 'billing#index',    as: :billing
  get '/organisation/billing/renew',   to: 'billing#renew_subscription',    as: :renew
  get '/organisation/billing/confirm', to: 'billing#confirm_payment', as: :confirm_payment

  resources :participations
  resources :users, only: [:show, :edit, :update]
  post '/users/:id/remove', to: 'users#remove_from_hoa', as: :remove_from_hoa
  post '/users/:id/change_role', to: 'users#change_role', as: :change_role

  get '/welcome', to: 'hoas#new', as: :welcome

  get   '/profile',         to: 'profile#index',  as: :profile
  get   '/profile/edit',    to: 'profile#edit',   as: :edit_profile
  patch '/profile/update',  to: 'profile#update', as: :update_profile

  get '/export', to: 'hoas#export', as: :export

  constraints(Subdomain) do
    get '/' => 'homepages#show', as: :public_homepage
  end

  root to: 'hoas#show'

  post '/ufgjdiie/:id', to: 'admin#change_hoa', as: :change_hoa

  require 'sidekiq/web'
  authenticate :user, lambda { |u| true } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/alert.rb
# == Schema Information
#
# Table name: alerts
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  body        :text
#  severity    :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  user_id     :integer
#  hoa_id      :integer
#  progress    :string(255)      default("new")
#  assignee_id :integer
#  archived    :boolean          default(FALSE)
#  attachment  :string(255)
#

class Alert < ActiveRecord::Base
  include Readable, Trackable

  # default_scope { where(archived: false) }

  # Validations
  validates :title,
            :user_id,
            :hoa_id,
            :progress,
            presence: true

  # active_admin
  resourcify

  # Acts as taggable on
  # preserve order so that in state, the last is the current state
  acts_as_ordered_taggable # Alias for acts_as_taggable_on :tags
  acts_as_ordered_taggable_on :state

  # Comments
  acts_as_commentable

  belongs_to :user
  belongs_to :assignee, class_name: 'User', foreign_key: :assignee_id
  belongs_to :hoa

  has_many :collaborations, as: :collaborable
  has_many :attachments, dependent: :destroy

  accepts_nested_attributes_for :attachments
  validates_associated :attachments

  def new?
    self.progress == 'new'
  end

  def in_progress?
    self.progress == 'in progress'
  end

  def completed?
    self.progress == 'completed'
  end

    def self.to_csv
    CSV.generate do |csv|
      csv << ['Melding Titel', 'Melding Beschrijving', 'Status', 'Gebruiker','Gemaakt','Reacties']
      all.each do |alert|
        csv << [
          alert.title,
          alert.body,
          alert.progress,
          alert.user.full_name,
          alert.created_at,
          alert.comments.pluck(:comment).join('; ').squish ]
      end
    end
  end
end

app/models/hoa.rb
# == Schema Information
#
# Table name: hoas
#
#  id                :integer          not null, primary key
#  name              :string(255)
#  created_at        :datetime
#  updated_at        :datetime
#  subdomain_name    :string(255)
#  subscription_type :string(255)      default("basic")
#  subscribed_until  :datetime
#  address           :string(255)
#  city              :string(255)
#  postal_code       :string(255)
#  kvk               :string(255)
#  account_nr        :string(255)
#  account_owner     :string(255)
#  allow_posts       :boolean          default(TRUE)
#

class Hoa < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper

  validates :name, :subdomain_name, presence: true
  validates :subdomain_name, uniqueness: true

  resourcify

  has_many :posts
  has_many :alerts
  has_many :users
  has_many :events
  has_many :announcements
  has_many :payments
  has_many :attachments
  has_one :homepage

  def subscription
    subscription_type == 'standard' ? 'Standaard' : 'Basis'
  end

  def subscribed?
    subscribed_until &&
    subscribed_until > DateTime.now &&
    subscription_type == 'standard'
  end

  def storage_used
    number_to_human_size(attachments.sum(:file_size))
  end
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  respond_to :html, :json

  before_filter :authenticate_user!
  before_action :set_alerts, only: [:index]
  before_action :set_alert,
    only: [:show, :edit, :update, :destroy, :remove_tag, :archive]
  before_action :set_assignees, only: [:create, :edit, :new]

  after_action :set_collaborators,  only: [:create, :update]
  after_action only: [:show] do
    @alert.mark_as_read!(current_user) unless @alert.read?(current_user)
  end

  # after_action :verify_authorized, except: [:index]

  # GET /alerts
  def index
  end

  # Get /alerts/archives
  def archives
  end

  # GET /alerts/1
  def show
    authorize @alert
    @comments = @alert.comments.includes(:user)
    @comment = Comment.new(user: current_user)

    @collaboration      = @alert.collaborations.find_by(user: current_user)
    @new_collaboration  = @alert.collaborations.new(user: current_user)
    @collaborations     = @alert.collaborations.includes(:user)

    @users = current_user.hoa.users
  end

  # GET /alerts/new
  def new
    @alert = Alert.new
    @alert_attachment = @alert.attachments.build
  end

  # GET /alerts/1/edit
  def edit
    authorize @alert
    @alert_attachment = @alert.attachments.build
  end

  # POST /alerts
  def create
    @alert = Alert.new(alert_params)
    @alert.user = current_user if current_user
    @alert.hoa  = current_user.hoa if current_user
    if @alert.save
      create_attachments
      set_collaborators
      notify_assignee
      redirect_to @alert, notice: I18n.t('alert.created')
    else
      render 'new', message: @alert.errors
    end
  end

  # PATCH/PUT /alerts/1
  def update
    authorize @alert
    progress_before = @alert.progress
    assignee_before = @alert.assignee

    @alert.assignee_id = alert_params[:assignee_id] if alert_params[:assignee_id] && current_user.has_role?(:moderator, @alert.hoa)

    if @alert.update(alert_params)
      on_assignee_change_notify(assignee_before)
      on_progress_change_post_comment(progress_before)
      create_attachments
      # If inline editing
      if request.xhr?
        respond_with @alert
      else
        redirect_to @alert, notice: I18n.t('alert.updated')
      end
    else
      render 'edit', alert: "Woops!"
    end
  end

  # DELETE /alerts/1
  def destroy
    authorize @alert
    @alert.destroy
    redirect_to alerts_path, notice: I18n.t('alert.destroyed')
  end

  # POST /alert/1/remove_tag
  def remove_tag
    session[:return_to] = request.referer
    @alert.tag_list.remove(params[:tag])
    @alert.save
    redirect_to session.delete(:return_to)
  end

  # POST /alert/1/archive
  def archive
    @alert.archived ? @alert.archived = false : @alert.archived = true
    if @alert.save
      redirect_to alerts_path
    else
      redirect_to alerts_path, alert: 'er ging iets fout'
    end
  end

  # PATCH /alerts/archive
  def archive_all
    Alert.where( id: params[:alert_ids], progress: 'completed' ).update_all({ archived: true })
    redirect_to alerts_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alert
      @alert = Alert.find(params[:id])
      @alert_attachments = @alert.attachments.all
    end

    def set_alerts
      params[:archive] ? query_alerts(true) : query_alerts(false)
    end

    def query_alerts(archived = false)
      @archived = archived
      if current_user.has_role?(:moderator, current_user.hoa)
        @alerts = current_user.hoa.alerts \
        .where(archived: archived) \
        .includes(:assignee, :user, :readings, taggings: [:tag]) \
        .order('alerts.updated_at DESC')
      else
        @alerts = current_user.hoa.alerts \
        .where(archived: archived) \
        .includes(:assignee, :user, :readings, taggings: [:tag]) \
        .order('alerts.updated_at DESC')
      end
    end

    def find_assignee(id)
      User.find(id)
    end

    # Only allow a trusted parameter "white list" through.
    def alert_params
      params.require(:alert).permit(:title, :body, :severity, :progress, :assignee_id, :tag_list, :tag, :user_id, :archive)
    end

    def set_assignees
      @assignees = current_user.hoa.users
    end

    def on_assignee_change_notify(assignee_before)
      notify_assignee unless assignee_before == @alert.assignee
    end

    def notify_assignee
      AssignmentMailer.delay.assigned_to_alert(current_user, @alert.assignee, @alert) if @alert.assignee
    end

    def on_progress_change_post_comment(progress_before)
      unless progress_before == @alert.progress
        @alert.create_activity(:progress_changed, owner: current_user, hoa_id: current_user.hoa.id, parameters: {progress_before: progress_before, progress_after: @alert.progress})

        Comment.public_activity_off
        comment = @alert.comments.create
        comment.comment = "heeft de status aangepast naar #{view_context.progress_name(@alert)}"
        comment.user = current_user
        comment.save
        Comment.public_activity_on
      end
    end

    def set_collaborators
      add_user_as_collaborator(current_user)
      add_user_as_collaborator(@alert.assignee) if @alert.assignee
    end

    def add_user_as_collaborator(user)
      @alert.collaborations.create(user: user) unless collaboration_exists?(user)
    end

    def collaboration_exists?(user)
      @alert.collaborations.exists?(user_id: user.id)
    end

    def create_attachments
      if params[:attachments]
        params[:attachments]['alert'].each do |a|
          @attachment = @alert.attachments.create(:attachment => a, :alert_id => @alert.id, hoa_id: @alert.hoa.id)
          if @attachment.errors.any?
            flash[:alert] = @attachment.errors.full_messages.first
          end
        end
      end
    end
end

app/helpers/alerts_helper.rb
module AlertsHelper
  def new_alert?(alert)
    alert.progress == 'new'
  end

  def alert_in_progress?(alert)
    alert.progress == 'in progress'
  end

  def alert_completed?(alert)
    alert.progress == 'completed'
  end

  def progress_name(alert)
    return I18n.t('alert.new') if new_alert?(alert)
    return I18n.t('alert.in_progress') if alert_in_progress?(alert)
    return I18n.t('alert.completed') if alert_completed?(alert)
  end

  def progress_name_from_string(string)
    return I18n.t('alert.new')            if string == 'new'
    return I18n.t('alert.in_progress')    if string == 'in progress'
    return I18n.t('alert.completed')      if string == 'completed'
    return I18n.t('alert.unknown_state')
  end

  def print_assignee(alert, options = {})
    if alert.assignee && options[:short]
      return alert.assignee.first_name
    elsif alert.assignee
      return alert.assignee.full_name
    else
      return t('alert.no_assignee')
    end
  end

  def print_assignee_short(alert)
    print_assignee(alert, short: true)
  end
end

app/views/alerts/_attendence_sidebar.html.haml
.ui.styled.sidebar
  - if @collaboration
    = link_to alert_collaboration_path(@alert, @collaboration), method: :delete, class: ' ui black fluid button' do
      Stop deelname

  - else
    = link_to alert_collaborations_path(@alert, @new_collaboration, collaboration: {user_id: current_user.id, collaborable_type: @alert.class, collaborable_id: @alert.id}), method: :post, class: 'ui positive fluid button' do
      Volg melding
  
  .ui.message
    Deelnemers worden op de hoogte gehouden van de status van deze melding.

  = form_for [@alert, @alert.collaborations.new], method: :post do |f|
    .ui.form
      .field
        %label
          Voeg een deelnemer toe
        = f.hidden_field :collaborable_type, value: @alert.class
        = f.hidden_field :collaborable_id,   value: @alert.id

        = f.select :user_id, @users.map {|u| [u.full_name, u.id]}, { include_blank: true }, {class: 'chosen-select', "data-placeholder" => 'Kies een deelnemer', "onchange" => "this.form.submit()" }

  .ui.menu
    .item.header
      = "Deelnemers (#{@collaborations.count})"

    - @collaborations.each do |collaboration|
      .item
        .ui.avatar.image
          = image_tag gravatar_url collaboration.user
        = link_to collaboration.user.full_name, user_path(collaboration.user)

app/views/alerts/_form.html.haml
= form_for(@alert) do |f|
  - if @alert.errors.any?
    .ui.error.message
      %ul
        - @alert.errors.full_messages.each do |msg|
          %li= msg

  .ui.form.alert

    .field
      %label
        = f.label 'Melding'
      .ui.left.input
        = f.text_field :title, autofocus: true

    .field
      %label
        = f.label 'Details'
      = f.text_area :body

    - if policy(@alert).assign?
      .field
        %label
          = f.label 'Toewijzen aan (deze persoon krijgt een email met deze melding)'
        = f.select :assignee_id, @assignees.map {|u| [u.full_name, u.id]}, { include_blank: true }, {class: 'chosen-select', "data-placeholder" => 'Selecteer iemand om die op de hoogte te brengen van deze melding' }

    .field
      %label
        = f.label 'Labels (komma tussen elk label)'
      = f.text_field :tag_list, class: 'form-control input-lg'

    = f.fields_for :attachments do |a|
      .field
        %label
          Uploads
        = a.file_field :attachment, multiple: true, name: "attachments[alert][]"


    .ui.buttons
      = f.submit 'Publiceer melding', class: 'ui positive button'
      = link_to 'Annuleer', (request.referrer || root_path), class: 'ui button'

    - if @alert.created_at
      = link_to 'Verwijder Melding', alert_path(@alert), class: 'ui negative button float-right', method: :delete

app/views/alerts/_show_top.html.haml
.ui.three.steps
  = link_to  'Nieuw', alert_path(alert, alert: { progress: "new" }), method: :patch, class: "state-toggle ui step #{'active' if alert.new?}", remote: true

  = link_to  'In behandeling', alert_path(alert, alert: { progress: "in progress" }), method: :patch, class: "state-toggle ui step #{'active' if alert.in_progress?}", remote: true
  
  = link_to  'Klaar', alert_path(alert, alert: { progress: "completed" }), method: :patch, class: "state-toggle ui step #{'active' if alert.completed?}", remote: true

app/views/alerts/_side.html.haml
- if policy(@alert).update?
  = link_to edit_alert_path(@alert), class: 'ui blue fluid button' do
    %i.edit.icon
    Melding aanpassen
.ui.secondary.segment
  .ui.selection.list
    .item
      .ui.avatar.image
        = image_tag gravatar_url @alert.user
      .content
        .header Melding door
        = link_to @alert.user.name, user_path(@alert.user)

    = link_to edit_alert_path(@alert), class: 'item' do
      .ui.avatar.image
        - if @alert.assignee
          = image_tag gravatar_url @alert.assignee
      .content
        .header
          Toegewezen aan
        = print_assignee_short @alert

    .item
      .content
        .header Melding aangemaakt
        = "#{format_time(@alert.created_at)} geleden"

    .item.toggle-sidebar
      .content
        .header Deelnemers
        = "#{@alert.collaborations.count} (klik voor details)"

.ui.fluid.labeled.icon.button.toggle-sidebar.lonely
  %i.ui.users.icon
  Wie kan deze melding zien?

// Archive button
= link_to alert_archive_path(@alert, id: @alert.id), method: :post, class: 'ui fluid labeled icon button lonely archive', remote: true do
  %i.archive.icon
  .text= @alert.archived ? 'Haal uit archief' : 'Archiveer'


// Notification button
- if @collaboration
  = link_to alert_collaboration_path(@alert, @collaboration), method: :delete, class: 'lonely ui fluid labeled icon button' do
    %i.stop.icon
    Stop notificaties

- else
  = link_to alert_collaborations_path(@alert, @new_collaboration, collaboration: {user_id: current_user.id, collaborable_type: @alert.class, collaborable_id: @alert.id}), method: :post, class: 'lonely ui fluid labeled icon button' do
    %i.mail.outline.icon
    Volg updates


// Upload button
- if policy(@alert).update?
  = link_to edit_alert_path(@alert), class: 'ui fluid labeled icon button' do
    %i.upload.icon
    Upload een bestand

app/views/alerts/_state_label.html.haml
- if new_alert? alert
  .ui.small.horizontal.red.label
    = progress_name alert
- elsif alert_in_progress? alert
  .ui.small.horizontal.purple.label
    = progress_name alert
- elsif alert_completed? alert
  .ui.small.horizontal.green.label
    = progress_name alert
- else
  .ui.small.horizontal.red.label
    Geen status

app/views/alerts/_table.html.haml
.ui.divided.selection.list.alert-list
  - alerts.each do |alert|
    - if alert.collaborations.where(user: current_user).exists?
      %li.item.listed-alert{ class: "#{'item listed-alert unread' if alert.unread?(current_user)}"}

        .state
          = render 'alerts/state_label', alert: alert

        .title
          = link_to truncate(alert.title, length: 74), alert

        .assignee.assignedfil
          = print_assignee_short alert

        .info
          .taglist.tagfil
            - alert.taggings.each do |tagging|
              .ui.tiny.label
                = tagging.tag.name

          .updated_at{ "data-content" => "#{alert.updated_at}", "data-variation" => 'small inverted' }
            = "Laatste update #{format_time(alert.updated_at)} geleden"

          .timestamp-hidden
            = alert.updated_at.to_i

          .ownedfil
            = alert.user.first_name

        - if policy(alert).update?
          .ui.tiny.basic.buttons
            = link_to 'Aanpassen', edit_alert_path(alert), class: 'ui button'
            .ui.tiny.blue.floating.dropdown.icon.button
              %i.dropdown.icon
              .menu
                .item
                  = link_to alert_archive_path(alert, id: alert.id), method: :post do
                    %i.archive.icon
                    = alert.archived ? 'Haal uit archief' : 'Archiveer'
                .item
                  = link_to alert, method: :delete, data: { confirm: 'Weet je zeker dat je deze melding wilt verwijderen?' } do
                    %i.delete.icon
                    Verwijder

app/views/alerts/edit.html.haml
.row
  .medium-12.small-12.medium-centered.column
    .ui.segment

      %h1 Pas melding aan
      = form_for(@alert) do |f|
        - if @alert.errors.any?
          .ui.error.message
            %ul
              - @alert.errors.full_messages.each do |msg|
                %li= msg

        .ui.form.alert

          .field
            %label
              = f.label 'Melding'
            .ui.left.input
              = f.text_field :title, autofocus: true

          .field
            %label
              = f.label 'Details'
            = f.text_area :body

          - if policy(@alert).assign?
            .field
              %label
                = f.label 'Toewijzen aan (deze persoon krijgt een email met deze melding)'
              = f.select :assignee_id, @assignees.map {|u| [u.full_name, u.id]}, { include_blank: true }, {class: 'chosen-select', "data-placeholder" => 'Selecteer iemand om die op de hoogte te brengen van deze melding' }

          .field
            %label
              = f.label 'Labels (komma tussen elk label)'
            = f.text_field :tag_list, class: 'form-control input-lg'

          .field
            %label
              Uploads
            = f.file_field :attachment, multiple: true, name: "attachments[alert][]"


          .ui.buttons
            = f.submit 'Publiceer melding', class: 'ui positive button'
            = link_to 'Annuleer', (request.referrer || root_path), class: 'ui button'

          - if @alert.created_at
            = link_to 'Verwijder Melding', alert_path(@alert), class: 'ui negative button float-right', method: :delete

app/views/alerts/index.html.haml
- @active_tab = 'alerts'
- @quick_add_bar = true
.row
  .medium-2.column
    .ui.small.fluid.vertical.menu
      .header.item
        %i.user.icon
        = current_user.first_name
      %a.item.ownedfilter.assignedfilter.active{ "data-filter" => "" } Alles
      %a.item.ownedfilter{ "data-filter" => "#{current_user.first_name}" } Aangemaakt
      %a.item.assignedfilter{ "data-filter" => "#{current_user.first_name}" } Toegewezen
      %a.item.assignedfilter{ "data-filter" => "niet toegewezen" }
        Niet toegewezen

    .ui.small.fluid.vertical.menu
      .header.item
        %i.list.layout.icon
        Status
      %a.item.filter.active{ "data-filter" => "" } Alles
      %a.item.filter{ "data-filter" => "nieuw" } Nieuw
      %a.item.filter{ "data-filter" => "in behandeling" } In behandeling
      %a.item.filter{ "data-filter" => "klaar" } Klaar

    - if @alerts.tag_counts
      .ui.small.fluid.vertical.menu
        .header.item
          %i.tags.icon
          Labels
        %a.item.tagfilter.active{ "data-filter" => ""} Alle labels
        - @alerts.tag_counts.order('taggings_count DESC').each do |tag|
          %a.item.tagfilter{ "data-filter" => "#{tag.name}"}
            .ui.label= tag.taggings_count
            = truncate(tag.name, length: 14)

  .medium-10.column#alerts-table
    .ui.icon.input.alert-search
      %input.search{ placeholder: 'Zoek op melding..' }
      %i.inverted.search.icon

    - unless @archived
      = link_to alerts_path(archive: true), class: 'ui labeled icon button float-right' do
        %i.archive.icon
        Archief
    - else
      = link_to alerts_path, class: 'ui labeled icon button float-right' do
        %i.list.icon
        Verlaat archief

    .ui.top.attached.segment

      .ui.selection.dropdown
        .text Sorteer op..
        %i.dropdown.icon
        .menu
          .item.sort{ "data-sort" => "timestamp-hidden" } Laatste Update
          .item.sort{ "data-sort" => "assignee" } Toegewezen
          .item.sort{ "data-sort" => "state" } Status

      .ui.selection.dropdown
        .text Aflopend
        %i.dropdown.icon
        .menu
          .item.sortorder{ "data-sort" => "desc" } Aflopend
          .item.sortorder{ "data-sort" => "asc" } Oplopend

      - if current_user.has_role?(:moderator, current_hoa) && ! @archived
        = link_to archive_all_alerts_path(alert_ids: @alerts.collect{ |a| a.id } ), data: { confirm: 'Weet je zeker dat je alles wilt archiveren dat op klaar staat?' }, method: :patch, class: 'ui basic animated button float-right' do
          .visible.content
            Archiveer alles op klaar
          .hidden.content
            %i.forward.icon

    .ui.attached.segment
      = render 'alerts/table', alerts: @alerts

app/views/alerts/new.html.haml
- @active_tab = 'add'
.row
  .medium-12.small-12.medium-centered.column
    .ui.segment
      %h1.ui.header 
        .content
          Nieuwe Melding
        .sub.header 
          Maak een melding aan. Deze kan later nog worden aangepast.

      = form_for(@alert) do |f|
        - if @alert.errors.any?
          .ui.error.message
            %ul
              - @alert.errors.full_messages.each do |msg|
                %li= msg

        .ui.form.alert

          .field
            %label
              = f.label 'Melding'
            .ui.left.input
              = f.text_field :title, autofocus: true

          .field
            %label
              = f.label 'Details'
            = f.text_area :body

          - if policy(@alert).assign?
            .field
              %label
                = f.label 'Toewijzen aan (deze persoon krijgt een email met deze melding)'
              = f.select :assignee_id, @assignees.map {|u| [u.full_name, u.id]}, { include_blank: true }, {class: 'chosen-select', "data-placeholder" => 'Selecteer iemand om die op de hoogte te brengen van deze melding' }

          .field
            %label
              = f.label 'Labels (komma tussen elk label)'
            = f.text_field :tag_list, class: 'form-control input-lg'

          = f.fields_for :attachments do |a|
            .field
              %label
                Uploads
              = a.file_field :attachment, multiple: true, name: "attachments[alert][]"


          .ui.buttons
            = f.submit 'Publiceer melding', class: 'ui positive button'
            = link_to 'Annuleer', (request.referrer || root_path), class: 'ui button'

          - if @alert.created_at
            = link_to 'Verwijder Melding', alert_path(@alert), class: 'ui negative button float-right', method: :delete

app/views/alerts/show.html.haml
.row
  .medium-8.column

    = render 'alerts/show_top', alert: @alert

    .ui.segment
      %h2.ui.header
        = inline_edit @alert, :title

      .alert-body
        = inline_edit(@alert, :body, 'textarea')

      - if @alert_attachments
        .ui.small.selection.list
          - @alert_attachments.each do |a|
            .item
              = link_to 'Verwijder', attachment_path(a), class: 'right floated ui mini basic button', method: :delete
              .content
                = link_to a.name, a.attachment_url

    - @alert.tags.each do |tag|
      .ui.label
        = tag.name
        = link_to alert_remove_tag_path(@alert, id: @alert.id, tag: tag.name), method: :post do
          %i.delete.icon

    = render 'comments/standard', comment: @comment, resource: @alert

  .medium-4.column
    = render 'alerts/side'


= render 'alerts/attendence_sidebar'